<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.80
        TextInput:
            size_hint_y: 0.10
        Button:
            text: 'Search Image'
            size_hint_y: 0.10
            on_press: root.search_image()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'